apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-acm-lpsre-admins-project
rules:
- apiGroups:
  - ''
  - apiextensions.k8s.io
  - apiregistration.k8s.io
  - apps
  - mcm.ibm.com
  resources:
  - configmaps
  - deployments
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  - apiregistration.k8s.io
  - apps
  resources:
  - configmaps
  - deployments
  - managedclusters
  - managedclustersets
  - multiclusterhubs
  - namespaces
  - pods
  - policyreports
  - services
  - subscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  - apps.open-cluster-management.io
  - clusterview.open-cluster-management.io
  - mcm.ibm.com
  - operator.open-cluster-management.io
  resources:
  - configmaps
  - deployments
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  - apiextensions.k8s.io
  - apiregistration.k8s.io
  - apps
  - apps.open-cluster-management.io
  resources:
  - channels
  - customresourcedefinitions
  - deployments
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  - apps
  resources:
  - deployments
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - search.open-cluster-management.io
  resources:
  - consolelinks
  - consoleplugins
  - searches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multicluster.openshift.io
  resources:
  - multiclusterengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - consoles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  - operatorgroups
  - subscriptions
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - multicluster-observability-operator
  resources:
  - deployments/finalizers
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - monitor.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.open-cluster-management.io
  resources:
  - '*'
  - multiclusterobservabilities
  - endpointmonitorings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  - routes/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - manageclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - 'list'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - clustermanagementaddons
  - clustermanagementaddons/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons
  verbs:
  - get
  - list
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - watch
  - get
  - list
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - multiclusterhubs
  verbs:
  - watch
  - get
  - list
- apiGroups:
  - imageregistry.open-cluster-management.io
  resources:
  - managedclusterimageregistries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - addondeploymentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - ''
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - namespaces
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclustersets
  verbs:
  - get
  - list
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - apiservers
  - infrastructures
  - infrastructures/status
  verbs:
  - get
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - clustermanagementaddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons
  verbs:
  - get
  - list
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons/finalizers
  verbs:
  - list
- apiGroups:
  - addon.open-cluster-management.io
  resources:
  - managedclusteraddons/status
  verbs:
  - list
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch

